# Generated by Django 3.2.5 on 2021-07-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_short', models.CharField(max_length=255)),
                ('description_long', models.TextField()),
                ('coordinates_lng', models.FloatField(default=0.0)),
                ('coordinates_lat', models.FloatField(default=0.0)),
            ],
        ),
    ]
