# Generated by Django 3.2.6 on 2021-09-01 01:44

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_remove_place_placeid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(max_length=255, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates_lat',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates_lng',
            field=models.FloatField(default=0.0, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
